### ISSUE TITLE
ModuleNotFoundError: No module named 'pysgg.modeling.roi_heads.relation_head.RTPB.utils'

### ISSUE THREAD

**Issue by wyz-gitt** [rafa-cxg/PySGG-cxg#1]
您好，我对您的工作非常感兴趣，但是我在运行您的程序的时候报错了，
raceback (most recent call last):
  File "tools/relation_train_net.py", line 28, in <module>
    from pysgg.modeling.detector import build_detection_model
  File "/home/wangyize/PySGG/pysgg/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/home/wangyize/PySGG/pysgg/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/home/wangyize/PySGG/pysgg/modeling/detector/generalized_rcnn.py", line 13, in <module>
    from pysgg.modeling.detector import build_detection_model
      File "/home/wangyize/PySGG/pysgg/modeling/detector/__init__.py", line 2, in <module>
from ..roi_heads.roi_heads import build_roi_heads
  File "/home/wangyize/PySGG/pysgg/modeling/roi_heads/roi_heads.py", line 8, in <module>
    from .detectors import build_detection_model
  File "/home/wangyize/PySGG/pysgg/modeling/detector/detectors.py", line 2, in <module>
    from .relation_head.relation_head import build_roi_relation_head
  File "/home/wangyize/PySGG/pysgg/modeling/roi_heads/relation_head/relation_head.py", line 18, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/home/wangyize/PySGG/pysgg/modeling/detector/generalized_rcnn.py", line 13, in <module>
    from ..roi_heads.roi_heads import build_roi_heads    
  File "/home/wangyize/PySGG/pysgg/modeling/roi_heads/roi_heads.py", line 8, in <module>
from .roi_relation_predictors import make_roi_relation_predictor
  File "/home/wangyize/PySGG/pysgg/modeling/roi_heads/relation_head/roi_relation_predictors.py", line 44, in <module>
    from .relation_head.relation_head import build_roi_relation_head
  File "/home/wangyize/PySGG/pysgg/modeling/roi_heads/relation_head/relation_head.py", line 18, in <module>
    from .RTPB.bias_module import build_bias_module
  File "/home/wangyize/PySGG/pysgg/modeling/roi_heads/relation_head/RTPB/bias_module.py", line 5, in <module>
        from .roi_relation_predictors import make_roi_relation_predictorfrom .utils import load_data
ModuleNotFoundError: No module named 'pysgg.modeling.roi_heads.relation_head.RTPB.utils'
Traceback (most recent call last):
  File "tools/relation_train_net.py", line 28, in <module>
    from pysgg.modeling.detector import build_detection_model
  File "/home/wangyize/PySGG/pysgg/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/home/wangyize/PySGG/pysgg/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/home/wangyize/PySGG/pysgg/modeling/detector/generalized_rcnn.py", line 13, in <module>
    from ..roi_heads.roi_heads import build_roi_heads
  File "/home/wangyize/PySGG/pysgg/modeling/roi_heads/roi_heads.py", line 8, in <module>
    from .relation_head.relation_head import build_roi_relation_head
  File "/home/wangyize/PySGG/pysgg/modeling/roi_heads/relation_head/relation_head.py", line 18, in <module>
    from .roi_relation_predictors import make_roi_relation_predictor
  File "/home/wangyize/PySGG/pysgg/modeling/roi_heads/relation_head/roi_relation_predictors.py", line 48, in <module>
    from .model_Hybrid_Attention import SHA_Context
  File "/home/wangyize/PySGG/pysgg/modeling/roi_heads/relation_head/model_Hybrid_Attention.py", line 6, in <module>
    from pysgg.modeling.roi_heads.relation_head.SHA.utils_co_attention import Self_Attention_Encoder, Cross_Attention_Encoder
ModuleNotFoundError: No module named 'pysgg.modeling.roi_heads.relation_head.SHA.utils_co_attention'
根据报错我找不到对应的 utils文件和co_attention'文件，请问您能解决吗
非常感谢

**Comment by rafa-cxg** [comment]
hi, we forgot to upload some files, now they should be available.

**Comment by wyz-gitt** [comment]
> 嗨，我们忘记上传一些文件，现在它们应该可用。

Thanks for your answer, but I have the problem again。


05/24 10:52:46 pysgg]: #################### end load checkpointer ####################
[05/24 10:52:46 pysgg]: #################### Start initializing dataset & dataloader ####################
[05/24 10:52:48 dataset]: using resampling method:bilvl
[05/24 10:52:48 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl
[05/24 10:52:48 dataset]: using resampling method:bilvl
[05/24 10:52:48 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl
[05/24 10:52:48 utils.miscellaneous]: Saving labels mapping into checkpoints/sgdet-BGNNPredictor/human_bgnn/labels.json
[05/24 10:52:50 dataset]: using resampling method:bilvl
[05/24 10:52:50 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl
[05/24 10:52:50 dataset]: using resampling method:bilvl
[05/24 10:52:50 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl
[05/24 10:52:50 utils.miscellaneous]: Saving labels mapping into checkpoints/sgdet-BGNNPredictor/human_bgnn/labels.json
[05/24 10:52:51 pysgg]: #################### end dataloader ####################
[05/24 10:52:51 pysgg]: #################### end distributed ####################
[05/24 10:52:51 pysgg]: Start preclser_relpn_pretrain
[05/24 10:52:51 pysgg]: Start training
Traceback (most recent call last):
  File "tools/relation_train_net.py", line 822, in <module>
    main()
  File "tools/relation_train_net.py", line 812, in main
    model = train(cfg, args.local_rank, args.distributed, logger)
  File "tools/relation_train_net.py", line 417, in train
    for iteration, (images, targets,_) in (enumerate(train_data_loader, start_iter)):
ValueError: too many values to unpack (expected 3)
根据报错可能是从数据集中读取图片和对应标签出现了问题，我运行原始的PySGG中的relation_train_net.py没报错，其中
.py文件中for iteration, (images, targets,_) in (enumerate(train_data_loader, start_iter)):跟您是一样的。请问您遇到过这个问题吗？感谢回复

**Comment by rafa-cxg** [comment]
> > 嗨，我们忘记上传一些文件，现在它们应该可用。
> 
> Thanks for your answer, but I have the problem again。
> 
> 05/24 10:52:46 pysgg]: #################### end load checkpointer #################### [05/24 10:52:46 pysgg]: #################### Start initializing dataset & dataloader #################### [05/24 10:52:48 dataset]: using resampling method:bilvl [05/24 10:52:48 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl [05/24 10:52:48 dataset]: using resampling method:bilvl [05/24 10:52:48 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl [05/24 10:52:48 utils.miscellaneous]: Saving labels mapping into checkpoints/sgdet-BGNNPredictor/human_bgnn/labels.json [05/24 10:52:50 dataset]: using resampling method:bilvl [05/24 10:52:50 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl [05/24 10:52:50 dataset]: using resampling method:bilvl [05/24 10:52:50 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl [05/24 10:52:50 utils.miscellaneous]: Saving labels mapping into checkpoints/sgdet-BGNNPredictor/human_bgnn/labels.json [05/24 10:52:51 pysgg]: #################### end dataloader #################### [05/24 10:52:51 pysgg]: #################### end distributed #################### [05/24 10:52:51 pysgg]: Start preclser_relpn_pretrain [05/24 10:52:51 pysgg]: Start training Traceback (most recent call last): File "tools/relation_train_net.py", line 822, in main() File "tools/relation_train_net.py", line 812, in main model = train(cfg, args.local_rank, args.distributed, logger) File "tools/relation_train_net.py", line 417, in train for iteration, (images, targets,_) in (enumerate(train_data_loader, start_iter)): ValueError: too many values to unpack (expected 3) 根据报错可能是从数据集中读取图片和对应标签出现了问题，我运行原始的PySGG中的relation_train_net.py没报错，其中 .py文件中for iteration, (images, targets,_) in (enumerate(train_data_loader, start_iter)):跟您是一样的。请问您遇到过这个问题吗？感谢回复

hi,这是一个bug，你可以按照这样修复（多加一个'_'）：
![image](https://user-images.githubusercontent.com/49938663/171991045-3e500119-704b-467c-8545-e57b22b1137b.png)

**Comment by wyz-gitt** [comment]
> > > 嗨，我们忘记上传一些文件，现在它们应该可用。
> > 
> > 
> > 谢谢你的回答，但我又有问题了。
> > 05/24 10：52：46 pysgg]： ###/24 10：52：48 数据集]： 使用重采样方法：bilvl [05/24 10：52：48 数据集]： 从检查点加载repeat_dict/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl [05/24 10：52：48 数据集]： 使用重采样方法：bilvl [05/24 10：52：48 数据集]： 加载repeat_dict来自 checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl [05/24 10：52：48 utils.miscellaneous]： 将标签映射保存到 checkpoints/sgdet-BGNNPredictor/human_bgnn/labels.json [05/24 10：52：50 dataset]： 使用重采样方法：bilvl [05/24 10：52：50 dataset]repeat_dict： 从 checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl [05/24 10：52：50 dataset]： 使用重采样方法：bilvl [05/24 10：52：50 数据集]： 从加载repeat_dict checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl [05/24 10：52：50 utils.miscellaneous]： 将标签映射成 checkpoints/sgdet-BGNNPredictor/human_bgnn/labels.json [05/24 10：52：51 pysgg]： ##############[05/24 10：52：51 pysgg]： ###preclser_relpn_pretrain# “tools/relation_train_net.py”， line 822， in main（） File “tools/relation_train_net.py”， line 812， in main model = train（cfg， args.local_rank， args.distributed， logger） File “tools/relation_train_net.py”， line 417， in train for iteration， （images， targets，_） in （enumerate（train_data_loader， start_iter））： ValueError： too many value to unpack （expected 3） 根据报错可能是从数据集中读取图片和对应标签出现了问题，我运行原始的PySGG中的relation_train_net.py没报错，其中 .py文件中为迭代， （图像、目标）_in （enumerate（train_data_loader， start_iter））：跟您是一样的。请问您遇到过这个问题吗？感谢回复
> 
> hi，这是一个bug，你可以按照这样修复（多加一个'_'）： ![图像](https://user-images.githubusercontent.com/49938663/171991045-3e500119-704b-467c-8545-e57b22b1137b.png)

非常感谢！！！！
