### ISSUE TITLE
KeyError:"image_paths"

### ISSUE THREAD

**Issue by shuizaola** [rafa-cxg/PySGG-cxg#2]
I'm very interested in your work, but I'm having a problem reproducing your code.
/20 19:37:22 pysgg]: #################### end load checkpointer ####################
[06/20 19:37:22 pysgg]: #################### Start initializing dataset & dataloader ####################
[06/20 19:37:24 dataset]: using resampling method:bilvl
[06/20 19:37:24 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl
[06/20 19:37:24 dataset]: using resampling method:bilvl
[06/20 19:37:24 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl
[06/20 19:37:24 utils.miscellaneous]: Saving labels mapping into checkpoints/sgdet-BGNNPredictor/human_bgnn/labels.json
[06/20 19:37:25 dataset]: using resampling method:bilvl
[06/20 19:37:25 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl
[06/20 19:37:25 dataset]: using resampling method:bilvl
[06/20 19:37:25 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl
[06/20 19:37:25 utils.miscellaneous]: Saving labels mapping into checkpoints/sgdet-BGNNPredictor/human_bgnn/labels.json
[06/20 19:37:26 pysgg]: #################### end dataloader ####################
[06/20 19:37:26 pysgg]: #################### end distributed ####################
[06/20 19:37:26 pysgg]: Start preclser_relpn_pretrain
[06/20 19:37:26 pysgg]: Start training
Traceback (most recent call last):
  File "tools/relation_train_net.py", line 822, in <module>
    main()
  File "tools/relation_train_net.py", line 812, in main
    model = train(cfg, args.local_rank, args.distributed, logger)
  File "tools/relation_train_net.py", line 430, in train
    loss_dict = model(images, targets, logger=logger) #predcls:dict:4
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
Traceback (most recent call last):
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
  File "tools/relation_train_net.py", line 822, in <module>
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/amp/_initialize.py", line 197, in new_fwd
    main()
  File "tools/relation_train_net.py", line 812, in main
    **applier(kwargs, input_caster))
  File "/home/pysgg/modeling/detector/generalized_rcnn.py", line 53, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets, logger)#CombinedROIHeads proposals:在100的基础上再加gt
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
        model = train(cfg, args.local_rank, args.distributed, logger)
result = self.forward(*input, **kwargs)
  File "tools/relation_train_net.py", line 430, in train
  File "/home/pysgg/modeling/roi_heads/roi_heads.py", line 79, in forward
    x, detections, loss_relation = self.relation(features=features, proposal=detections, targets=targets, logger=logger,**sampling)#ROIRelationHead:在这里proposal被采样.x:roi_feature[all_prop,4096]. detections:proposal
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    loss_dict = model(images, targets, logger=logger) #predcls:dict:4
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pysgg/modeling/roi_heads/relation_head/relation_head.py", line 233, in forward
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    union_features = self.union_feature_extractor(features, proposals,targets, rel_pair_idxs)#union包括所有的N!组合
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pysgg/modeling/roi_heads/relation_head/roi_relation_feature_extractors.py", line 143, in forward
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/amp/_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
  File "/home/pysgg/modeling/detector/generalized_rcnn.py", line 53, in forward
    img_path = targets[0].get_field('image_paths')
  File "/home//pysgg/structures/bounding_box.py", line 53, in get_field
    x, result, detector_losses = self.roi_heads(features, proposals, targets, logger)#CombinedROIHeads proposals:在100的基础上再加gt
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    return self.extra_fields[field]
KeyError: 'image_paths'
    result = self.forward(*input, **kwargs)
  File "/home/wyz/pysgg/modeling/roi_heads/roi_heads.py", line 79, in forward
    x, detections, loss_relation = self.relation(features=features, proposal=detections, targets=targets, logger=logger,**sampling)#ROIRelationHead:在这里proposal被采样.x:roi_feature[all_prop,4096]. detections:proposal
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home//pysgg/modeling/roi_heads/relation_head/relation_head.py", line 233, in forward
    union_features = self.union_feature_extractor(features, proposals,targets, rel_pair_idxs)#union包括所有的N!组合
  File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home//pysgg/modeling/roi_heads/relation_head/roi_relation_feature_extractors.py", line 143, in forward
    img_path = targets[0].get_field('image_paths')
  File "/home//pysgg/structures/bounding_box.py", line 53, in get_field
    return self.extra_fields[field]
KeyError: 'image_paths'
Have you encountered this problem, I will be very grateful if you solve this.
Thanks you!

**Comment by shuizaola** [comment]
> I'm very interested in your work, but I'm having a problem reproducing your code. /20 19:37:22 pysgg]: #################### end load checkpointer #################### [06/20 19:37:22 pysgg]: #################### Start initializing dataset & dataloader #################### [06/20 19:37:24 dataset]: using resampling method:bilvl [06/20 19:37:24 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl [06/20 19:37:24 dataset]: using resampling method:bilvl [06/20 19:37:24 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl [06/20 19:37:24 utils.miscellaneous]: Saving labels mapping into checkpoints/sgdet-BGNNPredictor/human_bgnn/labels.json [06/20 19:37:25 dataset]: using resampling method:bilvl [06/20 19:37:25 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl [06/20 19:37:25 dataset]: using resampling method:bilvl [06/20 19:37:25 dataset]: load repeat_dict from checkpoints/sgdet-BGNNPredictor/human_bgnn/repeat_dict.pkl [06/20 19:37:25 utils.miscellaneous]: Saving labels mapping into checkpoints/sgdet-BGNNPredictor/human_bgnn/labels.json [06/20 19:37:26 pysgg]: #################### end dataloader #################### [06/20 19:37:26 pysgg]: #################### end distributed #################### [06/20 19:37:26 pysgg]: Start preclser_relpn_pretrain [06/20 19:37:26 pysgg]: Start training Traceback (most recent call last): File "tools/relation_train_net.py", line 822, in main() File "tools/relation_train_net.py", line 812, in main model = train(cfg, args.local_rank, args.distributed, logger) File "tools/relation_train_net.py", line 430, in train loss_dict = model(images, targets, logger=logger) #predcls:dict:4 File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in **call** result = self.forward(*input, **kwargs) Traceback (most recent call last): File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 447, in forward File "tools/relation_train_net.py", line 822, in output = self.module(*inputs[0], **kwargs[0]) File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in **call** result = self.forward(*input, **kwargs) File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/amp/_initialize.py", line 197, in new_fwd main() File "tools/relation_train_net.py", line 812, in main **applier(kwargs, input_caster)) File "/home/pysgg/modeling/detector/generalized_rcnn.py", line 53, in forward x, result, detector_losses = self.roi_heads(features, proposals, targets, logger)#CombinedROIHeads proposals:在100的基础上再加gt File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in **call** model = train(cfg, args.local_rank, args.distributed, logger) result = self.forward(*input, **kwargs) File "tools/relation_train_net.py", line 430, in train File "/home/pysgg/modeling/roi_heads/roi_heads.py", line 79, in forward x, detections, loss_relation = self.relation(features=features, proposal=detections, targets=targets, logger=logger,**sampling)#ROIRelationHead:在这里proposal被采样.x:roi_feature[all_prop,4096]. detections:proposal File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in **call** loss_dict = model(images, targets, logger=logger) #predcls:dict:4 File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in **call** result = self.forward(*input, **kwargs) File "/home/pysgg/modeling/roi_heads/relation_head/relation_head.py", line 233, in forward result = self.forward(*input, **kwargs) File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 447, in forward union_features = self.union_feature_extractor(features, proposals,targets, rel_pair_idxs)#union包括所有的N!组合 File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in **call** output = self.module(*inputs[0], **kwargs[0]) File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in **call** result = self.forward(*input, **kwargs) File "/home/pysgg/modeling/roi_heads/relation_head/roi_relation_feature_extractors.py", line 143, in forward result = self.forward(*input, **kwargs) File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/amp/_initialize.py", line 197, in new_fwd **applier(kwargs, input_caster)) File "/home/pysgg/modeling/detector/generalized_rcnn.py", line 53, in forward img_path = targets[0].get_field('image_paths') File "/home//pysgg/structures/bounding_box.py", line 53, in get_field x, result, detector_losses = self.roi_heads(features, proposals, targets, logger)#CombinedROIHeads proposals:在100的基础上再加gt File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in **call** return self.extra_fields[field] KeyError: 'image_paths' result = self.forward(*input, **kwargs) File "/home/wyz/pysgg/modeling/roi_heads/roi_heads.py", line 79, in forward x, detections, loss_relation = self.relation(features=features, proposal=detections, targets=targets, logger=logger,**sampling)#ROIRelationHead:在这里proposal被采样.x:roi_feature[all_prop,4096]. detections:proposal File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in **call** result = self.forward(*input, **kwargs) File "/home//pysgg/modeling/roi_heads/relation_head/relation_head.py", line 233, in forward union_features = self.union_feature_extractor(features, proposals,targets, rel_pair_idxs)#union包括所有的N!组合 File "/home/anaconda3/envs/sgg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in **call** result = self.forward(*input, **kwargs) File "/home//pysgg/modeling/roi_heads/relation_head/roi_relation_feature_extractors.py", line 143, in forward img_path = targets[0].get_field('image_paths') File "/home//pysgg/structures/bounding_box.py", line 53, in get_field return self.extra_fields[field] KeyError: 'image_paths' Have you encountered this problem, I will be very grateful if you solve this. Thanks you!

 I add the code in relation_train_net.py in 417   
            "for iteration, (images, targets, _, _) in (enumerate(train_data_loader, start_iter)):"
it maybe add the "_" may be a problem with joining “_”，But if you don't add that code, there will be a problem of mismatched quantity

**Comment by shuizaola** [comment]
![image](https://user-images.githubusercontent.com/90588619/174708777-f6e79d69-dd00-4c6e-87cc-aa915cf33b58.png)

**Comment by rafa-cxg** [comment]
Yes, this bug (caused by adding visualization code) can be solved by modifying to:
`for iteration, (images, targets,_, _) in (enumerate(train_data_loader, start_iter)):`

I have submit new version to REPO

**Comment by rafa-cxg** [comment]
Yes, this bug can be solved by:
`for iteration, (images, targets,_, _) in (enumerate(train_data_loader, start_iter)):`
